[package]
name = "apper"
version = "0.2.0"
edition = "2024"
authors = ["Paul Sobolik <psobolik@zoho.com>"]
description = "Launch GUI apps from the command line"
license = "MIT"

[dependencies]
cursive = { version = "0.21.1" }
fork = "0.7.0"
regex = "1.11.3"
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread", "process"] }

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary
