[package]
name = "apper"
version = "0.1.0"
edition = "2024"

[dependencies]
configparser = "3.1.0"
cursive = { version = "0.21.1" }
regex = "1.11.3"
tokio = { version = "1.47.1", features = ["full"] }

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary